group = io.canvasmc.baguette

# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion = 26.1.2
mcVersion = 26.1.2
channel = STABLE

canvasCommit = 5746dad963f7d61af655ffbae2ab77dbe45b3700

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx4G
