group = io.canvasmc.baguette

# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion = 26.2
mcVersion = 26.2
channel = ALPHA

canvasCommit = 188aa2570df5809616fe37179197dde0607b7ee5

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx4G
